<?php
/**
 * search_expand.php — Arabic synonym-expanded search helper
 * ─────────────────────────────────────────────────────────────────────────────
 * Loads the pre-built ontology lookup (generated by tools/build_ontology_lookup.php)
 * and provides expandQuery() for use in search pages.
 *
 * Graceful degradation: if the lookup file is absent the search works normally
 * as a plain text search — no errors, no changed behaviour.
 *
 * Usage:
 *   require_once '/path/to/lib/search_expand.php';
 *   $terms = expandQuery($normalizedSearchTerm);   // array of terms to OR-search
 * ─────────────────────────────────────────────────────────────────────────────
 */

/** Load the ontology lookup once per process (OPcache-friendly). */
function _ak_getOntologyLookup(): array {
    static $lookup = null;
    if ($lookup !== null) return $lookup;
    $file = __DIR__ . '/ontology_lookup.php';
    $lookup = file_exists($file) ? (include $file) : [];
    return $lookup;
}

/**
 * Expand a normalised Arabic search string with ontology synonyms.
 *
 * - Splits the input into individual words and checks each against the lookup.
 * - Returns an array of normalised terms to use in OR-LIKE SQL conditions.
 * - The original term is always first in the result (highest relevance).
 * - Multi-word queries expand each word independently; all expansions are
 *   searched as full-phrase LIKE patterns (the expanded synonyms are single
 *   words, not phrases, so this gives wider recall without losing the original).
 * - Capped at MAX_EXPAND results to keep SQL clauses short.
 *
 * @param  string $norm  Already-normalised Arabic text (output of normalizeAr())
 * @return string[]      Array of normalised terms, length 1..MAX_EXPAND
 */
function expandQuery(string $norm): array {
    $lookup = _ak_getOntologyLookup();
    if (empty($lookup)) return [$norm];

    $terms = [$norm];   // original always first

    $words = preg_split('/\s+/u', $norm, -1, PREG_SPLIT_NO_EMPTY);
    foreach ($words as $word) {
        if (mb_strlen($word, 'UTF-8') < 2) continue;
        if (!isset($lookup[$word]))         continue;
        foreach ($lookup[$word] as $syn) {
            if (!in_array($syn, $terms, true)) {
                $terms[] = $syn;
                if (count($terms) >= 8) break 2;
            }
        }
    }

    return $terms;
}

/**
 * Build a SQL WHERE fragment that ORs multiple LIKE conditions.
 *
 * @param  string   $nc      The normalised SQL expression (output of normConcat())
 * @param  string[] $terms   Array from expandQuery()
 * @param  object   $db      mysqli or PDO instance (for escaping)
 * @param  string   $dbType  'mysqli' or 'pdo'
 * @return string            e.g. "expr LIKE '%a%' OR expr LIKE '%b%'"
 */
function buildLikeClause(string $nc, array $terms, $db, string $dbType = 'mysqli'): string {
    $clauses = [];
    foreach ($terms as $term) {
        if ($dbType === 'mysqli') {
            $escaped = $db->real_escape_string($term);
            $clauses[] = "$nc LIKE '%{$escaped}%'";
        } else {
            // PDO — caller should use $db->quote() and pass pre-quoted terms
            $quoted    = $db->quote('%' . $term . '%');
            $clauses[] = "$nc LIKE {$quoted}";
        }
    }
    return implode(' OR ', $clauses);
}
